import { KeyRound, LoaderCircle, LogIn, LogOut, ShieldCheck, UserRoundPlus } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";

import {
  AUTHENTICATION_REQUIRED_EVENT,
  ApiError,
  bootstrapBrowserAdministrator,
  loginBrowserAdministrator,
  logoutBrowserAdministrator,
  readBrowserAuthentication,
  type BrowserAuthenticationStatus,
} from "../lib/api";

interface AuthenticationFormProps {
  bootstrapRequired: boolean;
  bootstrapTokenRequired?: boolean;
  initialBootstrapToken?: string;
  busy: boolean;
  error: string | null;
  onSubmit: (input: { loginName: string; displayName?: string; password: string; bootstrapToken?: string }) => void;
  onRetry: () => void;
}

export function AuthenticationForm({
  bootstrapRequired,
  bootstrapTokenRequired = false,
  initialBootstrapToken = "",
  busy,
  error,
  onSubmit,
  onRetry,
}: AuthenticationFormProps) {
  const [loginName, setLoginName] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [bootstrapToken, setBootstrapToken] = useState(initialBootstrapToken);
  const [clientError, setClientError] = useState<string | null>(null);

  useEffect(() => {
    setClientError(null);
    setPassword("");
    setConfirmPassword("");
  }, [bootstrapRequired]);

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const normalizedLoginName = loginName.trim();
    const normalizedDisplayName = displayName.trim();
    if (!normalizedLoginName) {
      setClientError("Enter the administrator login name.");
      return;
    }
    if (bootstrapRequired && !normalizedDisplayName) {
      setClientError("Enter the administrator display name.");
      return;
    }
    if (bootstrapRequired && password !== confirmPassword) {
      setClientError("The administrator passwords do not match.");
      return;
    }
    setClientError(null);
    onSubmit({
      loginName: normalizedLoginName,
      ...(bootstrapRequired ? { displayName: normalizedDisplayName } : {}),
      ...(bootstrapRequired && bootstrapTokenRequired ? { bootstrapToken } : {}),
      password,
    });
  };

  return (
    <main className="session-auth-shell">
      <section className="session-auth-card" aria-labelledby="session-auth-title">
        <header>
          <span className="session-auth-mark"><ShieldCheck size={25} /></span>
          <div>
            <p>FormaSpec</p>
            <h1 id="session-auth-title">{bootstrapRequired ? "Create the first administrator" : "Sign in to FormaSpec"}</h1>
            <span>AI-first product design, specification, and engineering handoff.</span>
          </div>
        </header>

        <div className="session-auth-security-note" id="session-auth-security-note">
          <KeyRound size={17} />
          <span>{bootstrapRequired
            ? "This one-time setup creates the Organization Administrator who can create, edit, import, back up, and manage designs."
            : "Use the administrator account created during first-time setup. Agent credentials remain separate and revocable."}</span>
        </div>

        <form aria-busy={busy} aria-describedby="session-auth-security-note" onSubmit={submit}>
          {bootstrapRequired && (
            <label>
              <span>Display name</span>
              <input
                autoComplete="name"
                autoFocus
                dir="auto"
                maxLength={120}
                minLength={1}
                required
                value={displayName}
                onChange={(event) => { setDisplayName(event.target.value); setClientError(null); }}
                placeholder="FormaSpec Administrator"
              />
            </label>
          )}
          {bootstrapRequired && bootstrapTokenRequired && (
            <label>
              <span>One-time setup code</span>
              <input
                autoCapitalize="none"
                autoComplete="one-time-code"
                autoCorrect="off"
                maxLength={256}
                minLength={32}
                required
                spellCheck={false}
                type="password"
                value={bootstrapToken}
                onChange={(event) => { setBootstrapToken(event.target.value); setClientError(null); }}
                placeholder="Generated by ./designer server init"
              />
              <small className="session-auth-field-help">The startup link loads this one-time code, removes it from the address bar, and never stores it as the administrator password.</small>
            </label>
          )}
          <label>
            <span>Login name</span>
            <input
              autoCapitalize="none"
              autoComplete="username"
              autoCorrect="off"
              maxLength={128}
              minLength={3}
              required
              spellCheck={false}
              value={loginName}
              autoFocus={!bootstrapRequired}
              onChange={(event) => { setLoginName(event.target.value); setClientError(null); }}
              placeholder="admin@example.com"
            />
          </label>
          <label>
            <span>Password</span>
            <input
              autoComplete={bootstrapRequired ? "new-password" : "current-password"}
              maxLength={256}
              minLength={12}
              required
              type="password"
              value={password}
              onChange={(event) => { setPassword(event.target.value); setClientError(null); }}
              placeholder="At least 12 characters"
            />
          </label>
          {bootstrapRequired && (
            <label>
              <span>Confirm password</span>
              <input
                autoComplete="new-password"
                maxLength={256}
                minLength={12}
                required
                type="password"
                value={confirmPassword}
                onChange={(event) => { setConfirmPassword(event.target.value); setClientError(null); }}
                placeholder="Enter the same password again"
              />
            </label>
          )}

          {(clientError ?? error) && <div className="session-auth-error" role="alert">{clientError ?? error}</div>}

          <button className="button button-primary session-auth-submit" disabled={busy} type="submit">
            {busy ? <LoaderCircle className="spin" size={17} /> : bootstrapRequired ? <UserRoundPlus size={17} /> : <LogIn size={17} />}
            {bootstrapRequired ? "Create administrator" : "Sign in"}
          </button>
          {error && !clientError && <button className="session-auth-retry" disabled={busy} type="button" onClick={onRetry}>Check server status</button>}
        </form>

        <footer>
          <strong>Self-hosted and private</strong>
          <span>Passwords and browser-session tokens are stored only as hardened hashes. FormaSpec does not store an OpenAI API key.</span>
        </footer>
      </section>
    </main>
  );
}

export function parseBootstrapTokenFragment(fragment: string): string | null {
  const serialized = fragment.startsWith("#") ? fragment.slice(1) : fragment;
  const parameters = new URLSearchParams(serialized);
  if ([...parameters.keys()].some((key) => key !== "bootstrap") || parameters.getAll("bootstrap").length !== 1) return null;
  const token = parameters.get("bootstrap");
  return token && /^[A-Za-z0-9._-]{32,256}$/.test(token) ? token : null;
}

function AuthenticationLoading() {
  return (
    <main className="session-auth-shell">
      <div className="session-auth-loading"><LoaderCircle className="spin" size={25} /><strong>Starting FormaSpec</strong><span>Checking the local workspace and administrator session…</span></div>
    </main>
  );
}

function AuthenticationUnavailable({ error, onRetry }: { error: string; onRetry: () => void }) {
  return (
    <main className="session-auth-shell">
      <section className="session-auth-card session-auth-unavailable" role="alert">
        <span className="session-auth-mark"><ShieldCheck size={25} /></span>
        <h1>FormaSpec could not start</h1>
        <p>{error}</p>
        <button className="button button-primary" onClick={onRetry} type="button">Check server status</button>
      </section>
    </main>
  );
}

export function SessionAuthentication({ children }: { children: ReactNode }) {
  const [bootstrapToken, setBootstrapToken] = useState(() => {
    const hasBootstrapParameter = new URLSearchParams(window.location.hash.replace(/^#/, "")).has("bootstrap");
    const token = parseBootstrapTokenFragment(window.location.hash);
    if (hasBootstrapParameter) {
      window.history.replaceState({}, "", `${window.location.pathname}${window.location.search}`);
    }
    return token ?? "";
  });
  const [status, setStatus] = useState<BrowserAuthenticationStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      setStatus(await readBrowserAuthentication());
      setError(null);
    } catch (cause) {
      setStatus(null);
      setError(cause instanceof Error ? cause.message : "Could not check the FormaSpec administrator session.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void refresh();
    const authenticationRequired = () => void refresh();
    window.addEventListener(AUTHENTICATION_REQUIRED_EVENT, authenticationRequired);
    return () => window.removeEventListener(AUTHENTICATION_REQUIRED_EVENT, authenticationRequired);
  }, [refresh]);

  const submit = async (input: { loginName: string; displayName?: string; password: string; bootstrapToken?: string }) => {
    if (!status) return;
    setBusy(true);
    setError(null);
    try {
      const next = status.bootstrapRequired
        ? await bootstrapBrowserAdministrator(input)
        : await loginBrowserAdministrator({ loginName: input.loginName, password: input.password });
      setStatus(next);
      if (next.authenticated) setBootstrapToken("");
    } catch (cause) {
      if (status.bootstrapRequired && cause instanceof ApiError && cause.code === "VERSION_CONFLICT") {
        try {
          const latest = await readBrowserAuthentication();
          setStatus(latest);
          if (!latest.bootstrapRequired) {
            setBootstrapToken("");
            setError("Administrator setup is already complete. Sign in with the account created for this FormaSpec workspace.");
          } else {
            setError(cause.message);
          }
        } catch {
          setError(cause.message);
        }
      } else {
        setError(cause instanceof Error ? cause.message : "FormaSpec could not complete authentication.");
      }
    } finally {
      setBusy(false);
    }
  };

  const logout = async () => {
    setBusy(true);
    setError(null);
    try {
      await logoutBrowserAdministrator();
      await refresh();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "FormaSpec could not sign out this session.");
    } finally {
      setBusy(false);
    }
  };

  if (loading && !status) return <AuthenticationLoading />;
  if (!status) {
    return <AuthenticationUnavailable error={error ?? "FormaSpec is unavailable."} onRetry={() => void refresh()} />;
  }
  if (status.mode === "session" && !status.authenticated) {
    return <AuthenticationForm bootstrapRequired={status.bootstrapRequired} bootstrapTokenRequired={status.bootstrapTokenRequired} initialBootstrapToken={bootstrapToken} busy={busy} error={error} onSubmit={(input) => void submit(input)} onRetry={() => void refresh()} />;
  }

  return (
    <>
      {children}
      {status.mode === "session" && status.account && (
        <aside className="session-account-badge" aria-label="Signed-in administrator">
          <span><ShieldCheck size={14} /><span><strong>{status.account.displayName}</strong><small>{status.account.role.replaceAll("_", " ")}</small></span></span>
          <button disabled={busy} onClick={() => void logout()} type="button" aria-label="Sign out of FormaSpec">
            {busy ? <LoaderCircle className="spin" size={14} /> : <LogOut size={14} />}
            Sign out
          </button>
          {error && <em role="alert">{error}</em>}
        </aside>
      )}
    </>
  );
}
